# Generated by Django 6.0.4 on 2026-07-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindb',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='maindb',
            old_name='added_on',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='maindb',
            name='title',
        ),
    ]
